openapi: 3.1.0
info:
  title: Huella Rural API
  description: Huella Rural API
  version: 0.0.1
  contact:
    name: Huella Rural
    email: icesarani@uade.edu.ar
servers:
  - url: http://localhost:3000
security:
  - cookieAuth: []
  - bearerAuth: []
tags:
  - name: Auth
    description: Endpoints for user authentication.
paths:
  /api/v1/sessions:
    post:
      summary: Creates a new session.
      description: Creates a new session for the user.
      operationId: createSession
      tags: [Auth]
      requestBody:
        description: Viewer credentials for authentication.
        required: true
        content:
          application/json:
            schema:
              type: object
              properties:
                user:
                  type: object
                  properties:
                    email:
                      type: string
                      format: email
                      description: The user's email address.
                      example: jdoe@gmail.com
                    password:
                      type: string
                      format: password
                      description: The user's password.
                      example: securePassword123
                  required:
                    - email
                    - password
              required:
                - user
      responses:
        '200':
          description: Successfully authenticated. The session token is sent as a cookie and JWT token in Authorization header.
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/User'
        '401':
          description: Invalid email or password.
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/Error'
    delete:
      summary: Deletes the current session.
      description: Deletes the current session for the user.
      operationId: deleteSession
      tags: [Auth]
      responses:
        '204':
          description: Successfully deleted the session.
  /api/v1/registrations:
    post:
      summary: Creates a new user registration.
      description: Creates a new user account and returns the user information.
      operationId: createRegistration
      tags: [Auth]
      requestBody:
        description: User registration data.
        required: true
        content:
          application/json:
            schema:
              type: object
              properties:
                user:
                  type: object
                  properties:
                    email:
                      type: string
                      format: email
                      description: The user's email address.
                      example: jdoe@gmail.com
                    password:
                      type: string
                      format: password
                      description: The user's password.
                      example: securePassword123
                    producer_profile_attributes:
                      $ref: '#/components/schemas/ProducerProfileAttributes'
                    vet_profile_attributes:
                      $ref: '#/components/schemas/VetProfileAttributes'
                  required:
                    - email
                    - password
              required:
                - user
      responses:
        '200':
          description: Successfully created user account. JWT token included in Authorization header.
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/User'
        '422':
          description: Validation errors.
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/Error'
components:
  securitySchemes:
    cookieAuth:
      type: apiKey
      in: cookie
      name: _huella_api_session
    bearerAuth:
      type: http
      scheme: bearer
      bearerFormat: JWT
  schemas:
    User:
      type: object
      properties:
        id:
          type: integer
          description: The unique identifier of the user.
          example: 1
        email:
          type: string
          format: email
          description: The user's email address.
          example: "icesarani@uade.edu.ar"
        producer_profile:
          $ref: '#/components/schemas/ProducerProfile'
          description: Producer profile information (if user is a producer)
        vet_profile:
          $ref: '#/components/schemas/VetProfile'
          description: Vet profile information (if user is a vet)
    ProducerProfile:
      type: object
      properties:
        id:
          type: integer
          description: Profile identifier
          example: 1
        name:
          type: string
          description: Producer name
          example: "Juan Pérez"
        cuig_number:
          type: string
          description: CUIG number
          example: "CUIG123456"
        renspa_number:
          type: string
          description: RENSPA number
          example: "RENSPA12345"
        identity_card:
          type: string
          description: Identity card number
          example: "12345678"
        created_at:
          type: string
          format: date-time
          description: Profile creation timestamp
          example: "2024-01-15T10:30:00Z"
        updated_at:
          type: string
          format: date-time
          description: Profile last update timestamp
          example: "2024-01-15T10:30:00Z"
    VetProfile:
      type: object
      properties:
        id:
          type: integer
          description: Profile identifier
          example: 1
        first_name:
          type: string
          description: Veterinarian first name
          example: "María"
        last_name:
          type: string
          description: Veterinarian last name
          example: "González"
        full_name:
          type: string
          description: Veterinarian full name
          example: "María González"
        license_number:
          type: string
          description: Veterinarian license number
          example: "LIC123456"
        identity_card:
          type: string
          description: Identity card number
          example: "87654321"
        created_at:
          type: string
          format: date-time
          description: Profile creation timestamp
          example: "2024-01-15T10:30:00Z"
        updated_at:
          type: string
          format: date-time
          description: Profile last update timestamp
          example: "2024-01-15T10:30:00Z"
        localities:
          type: array
          description: Localities where the vet provides services
          items:
            $ref: '#/components/schemas/Locality'
    ProducerProfileAttributes:
      type: object
      properties:
        name:
          type: string
          description: Producer name
          example: "Juan Pérez"
        cuig_number:
          type: string
          description: CUIG number
          example: "CUIG123456"
        renspa_number:
          type: string
          description: RENSPA number
          example: "RENSPA12345"
        identity_card:
          type: string
          description: Identity card number
          example: "12345678"
      required:
        - name
        - cuig_number
        - renspa_number
        - identity_card
    VetProfileAttributes:
      type: object
      properties:
        first_name:
          type: string
          description: Veterinarian first name
          example: "María"
        last_name:
          type: string
          description: Veterinarian last name
          example: "González"
        license_number:
          type: string
          description: Veterinarian license number
          example: "LIC123456"
        identity_card:
          type: string
          description: Identity card number
          example: "87654321"
        vet_service_areas_attributes:
          type: array
          description: Optional array of service areas for the veterinarian
          items:
            $ref: '#/components/schemas/VetServiceAreaAttributes'
          example:
            - locality_id: 1
            - locality_id: 2
      required:
        - first_name
        - last_name
        - license_number
        - identity_card
    VetServiceAreaAttributes:
      type: object
      properties:
        locality_id:
          type: integer
          description: The ID of the locality where the veterinarian provides services
          example: 1
      required:
        - locality_id
    Locality:
      type: object
      properties:
        id:
          type: integer
          description: Locality identifier
          example: 1
        name:
          type: string
          description: Locality name
          example: "Buenos Aires"
        province_id:
          type: integer
          description: Province identifier
          example: 1
    Error:
      type: object
      properties:
        errors:
          type: object
          description: Validation errors
          additionalProperties: true
          example: 
            profile_type: ["debes especificar si eres productor o veterinario"]
