# PostgreSQL db from container
default: &default
  adapter: postgresql
  encoding: unicode
  pool: 5
  username: <%= ENV['DATABASE_USERNAME'] %>
  password: <%= ENV['DATABASE_PASSWORD'] %>
  host: <%= ENV['DATABASE_HOST'] %>

development:
  <<: *default
  database: huella_api_development

test:
  <<: *default
  database: huella_api_test

production:
  <<: *default
  database: huella_api_production
